### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by captjt** [USStateDept/edip-misc#161]
Tasks for incorporating Jenkins into our stack
====================

- [x] Standing up and configure Jenkins locally for plugin dependencies
- [x] Integrate a pipeline for testing/displaying test coverage "post" pipeline [#162](https://github.com/USStateDept/edip-misc/issues/162)

AWS (Live Instance of Jenkins)
====================

- [x] Stand up Jenkins and configured it for build agents (add ticket here)
- [x] Encrypt Jenkins Server [#165](https://github.com/USStateDept/edip-misc/issues/165)

MISC
====================
- [x] Write up on encrypting Jenkins [#166](https://github.com/USStateDept/edip-misc/issues/166)
